version: "3.2"
services:
  neo4j:
    restart: always
    image: neo4j
    ports:
      - "7471:7474"
      - "7687:7687"
    expose: 
      - 7471
      - 7681
    volumes: 
      - ../neo4j/data:/var/lib/neo4j/data
    networks: 
      - compose-kafka-manager_dataflow

  server:
    restart: always
    build: .
    entrypoint: python3 -m src.global_server
    links: 
      - neo4j:n4j
    environment:
      LOG: 'DEB'
      BROKERS: kafka_1:9090,kafka_2:9090,kafka_3:9090
      GROUP_ID: n4jserver
      REQUEST_TOPIC: neo4j-request
      RESPONSE_TOPIC: neo4j-response
      FAIL_TOPIC: neo4j-onfail
      NEO4J_USER: neo4j
      NEO4J_PASS: data1
      NEO4J_URI: bolt://neo4j:7687
    networks: 
      - compose-kafka-manager_dataflow

  sync:
    restart: always
    build: .
    entrypoint: python3 -m src.db_sync.py
    links: 
      - neo4j:n4j
    environment:
      LOG: 'DEB'
      BROKERS: kafka_1:9090,kafka_2:9090,kafka_3:9090
      GROUP_ID: n4jserver
      REQUEST_TOPIC: neo4j-command
      RESPONSE_TOPIC: neo4j-command-response
      FAIL_TOPIC: neo4j-command-fail
      NEO4J_USER: neo4j
      NEO4J_PASS: data1
      NEO4J_URI: bolt://neo4j:7687
    networks: 
      - compose-kafka-manager_dataflow

    

networks:
  compose-kafka-manager_dataflow:
    external: true
